# These are supported funding model platforms — GitHub renders a "Sponsor"
# button at the top of the repo from this file. See:
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
custom: ["https://venmo.com/u/travispflanz?txn=pay&amount=5&note=Thanks+for+mfl-fcfs-rolling-waiver-order"]
